"""
 * cros project                                              https://github.com/ProjectCros/cros
 * (c) 2016 Py64 <py64.wolflinux@gmail.com>                  https://github.com/Py64
 *
 * This software is distributed on CPL license.
 * https://github.com/ProjectCros/CPL
"""
# Do not edit this file!
from lib.releaseinfo import *
from lib import Out, Reaper
if Final: Version = FinalVersion
else: Version = VersionNo + Revision

def Show(config):
    Out.log(config.MainLog, "cros " + Version, True)
    if Insecure == True: Out.log(config.MainLog, "Insecure flag is on. If you did not enabled it, check your installation for malicious code. If it was you, you run cros at your own risk.", True)
