# Do not edit this file!
from lib.releaseinfo import *
from lib import Out
if Final: Version = FinalVersion
else: Version = DetailedVersion
def Show(config):
    Out.log(config.MainLog, "cros " + Version + "\nBuild date: " + BuildDate, True)
    if Insecure == True: Out.log(config.MainLog, "Insecure flag is on. If you did not enabled it, check your installation for malicious code. If it was you, you run cros at your own risk.", True)
